language: ruby
rvm:
- 2.1.5
env:
- DB=postgresql
bundler_args: "--without development --binstubs"
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec
before_script:
- cp config/database.travisci.yml config/database.yml
- cp config/application.example.yml config/application.yml
- psql -c 'create database claude_test' -U postgres
