development:
  adapter: sqlite3
  database: db/claude_development.sqlite3 
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/claude_test.sqlite3 
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: claude_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
